[package]
name = "ieee80211"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2021"


[dependencies]
eui48 = "1"
byteorder = "1"

[dev-dependencies]
criterion = "0.5"


[features]
"serde" = ["eui48/serde"]

[[bench]]
name = "main_benchmark"
harness = false
